#spring.application.name :blog
spring.data.mongodb.uri : mongodb+srv://Rohit:lywUh1a1SQtRSuzw@atlascluster.mldnioh.mongodb.net/?retryWrites=true&w=majority&appName=AtlasCluster
spring.data.mongodb.database : travelBlogDB

# src/main/resources/application.properties
spring.servlet.multipart.enabled: true
spring.servlet.multipart.max-file-size: 10MB
spring.servlet.multipart.max-request-size: 10MB
  
jwt-secret-key: travelBlogSecret